// ---------------------------------------------------------------------------
// API INTEGRATION REGISTRY
//
// Central registry of every capability the workbench knows about.
// New sources are added HERE only - the scan engines read from this file,
// so adding a source never requires modifying the scan engine.
//
// Status labels used in the UI:
//   verified      - live tested against the official endpoint (Sept 2026)
//   docs-verified - official docs/repo confirm the interface; endpoint not
//                   reachable from this build sandbox but works on open
//                   networks (the app degrades gracefully when unreachable)
//   local         - runs entirely on the user's machine
//   optional-key  - keyless works; an optional key raises rate limits
//   key-required  - KEY REQUIRED, optional only
//   paid          - PAID, documented as future work only
//   unavailable   - dead / deprecated / automation prohibited
// ---------------------------------------------------------------------------

import type { Integration } from "./types";

export const INTEGRATIONS: Integration[] = [
  // =========================================================================
  // TIER 1 — FREE + KEYLESS + OFFICIALLY SUPPORTED (default scan)
  // =========================================================================

  // ---- Local analysis (always works, no network) -------------------------
  {
    id: "local-dns",
    name: "Local DNS resolver (OS)",
    category: "domain",
    tier: "tier1",
    keyRequired: false,
    accountRequired: false,
    paid: false,
    status: "local",
    officialDocumentation: "https://nodejs.org/api/dns.html",
    repository: "https://github.com/nodejs/node",
    rateLimit: "None (uses the machine's configured resolver)",
    automation: "permitted",
    input: "domain name",
    output: "A / AAAA / MX / TXT / NS / CNAME / SOA records",
    implementation: "dns",
    limitations: "Answers come from the machine's recursive resolver; view may differ by network.",
    defaultEnabled: true,
    lastVerified: "2026-09-03",
  },
  {
    id: "local-whois",
    name: "WHOIS (TCP/43, RFC 3912)",
    category: "domain",
    tier: "tier1",
    keyRequired: false,
    accountRequired: false,
    paid: false,
    status: "docs-verified",
    officialDocumentation: "https://datatracker.ietf.org/doc/html/rfc3912",
    rateLimit: "Informal; queries are cheap, always rate-limited client-side",
    automation: "permitted-rate-limited",
    input: "domain or IP",
    output: "Registrar, creation/expiry dates, nameservers, registrant (where published)",
    implementation: "whois-tcp43",
    limitations: "Port 43 is blocked on some corporate networks; many TLDs redact data (GDPR).",
    defaultEnabled: true,
    lastVerified: "2026-09-03",
  },
  {
    id: "local-phash",
    name: "Local perceptual image hash (aHash/dHash/pHash)",
    category: "image",
    tier: "tier1",
    keyRequired: false,
    accountRequired: false,
    paid: false,
    status: "local",
    officialDocumentation: "https://www.hackerfactor.com/blog/index.php?/archives/529-Kind-of-Like-That.html",
    rateLimit: "None",
    automation: "permitted",
    input: "image file (JPEG/PNG/WebP/GIF/BMP/TIFF/AVIF)",
    output: "64-bit hashes + Hamming distance comparison",
    implementation: "local",
    limitations: "Hashing is robust to rescaling/compression but not to crops or rotation.",
    defaultEnabled: true,
    lastVerified: "2026-09-03",
  },
  {
    id: "local-exif",
    name: "Local EXIF/metadata extraction (exifr)",
    category: "image",
    tier: "tier1",
    keyRequired: false,
    accountRequired: false,
    paid: false,
    status: "local",
    officialDocumentation: "https://github.com/MikeKovarik/exifr",
    repository: "https://github.com/MikeKovarik/exifr",
    rateLimit: "None",
    automation: "permitted",
    input: "image file",
    output: "EXIF, XMP, ICC, GPS, camera make/model, timestamps",
    implementation: "local",
    limitations: "Stripped images (most social media) yield little metadata.",
    defaultEnabled: true,
    lastVerified: "2026-09-03",
  },
  {
    id: "local-normalize",
    name: "Local email/username normalization & correlation",
    category: "correlation",
    tier: "tier1",
    keyRequired: false,
    accountRequired: false,
    paid: false,
    status: "local",
    officialDocumentation: "https://github.com/frankb3511-eng/new (this project)",
    rateLimit: "None",
    automation: "permitted",
    input: "email address / username",
    output: "Normalized forms, provider detection, disposable-domain flags",
    implementation: "local",
    limitations: "Normalization rules are provider-specific; conservative matches only.",
    defaultEnabled: true,
    lastVerified: "2026-09-03",
  },

  // ---- Code / developer profiles -----------------------------------------
  {
    id: "github",
    name: "GitHub REST API v3 (users)",
    category: "code-registry",
    tier: "tier1",
    keyRequired: false,
    accountRequired: false,
    paid: false,
    status: "verified",
    officialDocumentation: "https://docs.github.com/en/rest/users/users#get-a-user",
    repository: "https://github.com/github/rest-api-description",
    rateLimit: "60 req/hour per IP unauthenticated; 5,000 with a free token",
    automation: "permitted-rate-limited",
    input: "username",
    output: "Profile, bio, location, blog/links, company, avatar, follower count, creation date",
    implementation: "https-json",
    limitations: "404 for non-existent users; some profile fields are optional.",
    defaultEnabled: true,
    lastVerified: "2026-09-03",
  },
  {
    id: "github-events",
    name: "GitHub public event feed",
    category: "code-registry",
    tier: "tier1",
    keyRequired: false,
    accountRequired: false,
    paid: false,
    status: "verified",
    officialDocumentation: "https://docs.github.com/en/rest/activity/events#list-public-events-for-a-user",
    rateLimit: "Shared 60 req/hour/IP unauthenticated",
    automation: "permitted-rate-limited",
    input: "username",
    output: "Recent public activity (pushes, PRs, issues) with timestamps and repos",
    implementation: "https-json",
    limitations: "Only the most recent ~90 days / 300 events; empty for inactive users.",
    defaultEnabled: true,
    lastVerified: "2026-09-03",
  },
  {
    id: "gitlab",
    name: "GitLab REST API v4 (users)",
    category: "code-registry",
    tier: "tier1",
    keyRequired: false,
    accountRequired: false,
    paid: false,
    status: "verified",
    officialDocumentation: "https://docs.gitlab.com/api/users/#list-users",
    repository: "https://gitlab.com/gitlab-org/gitlab",
    rateLimit: "Anonymous requests allowed; rate limited per IP (2,000 req/min authenticated)",
    automation: "permitted-rate-limited",
    input: "username",
    output: "Profile, name, bio, location, avatar, web URLs, last activity",
    implementation: "https-json",
    limitations: "Anonymous search returns a single exact-match user; 200 + [] means not found.",
    defaultEnabled: true,
    lastVerified: "2026-09-03",
  },
  {
    id: "keybase",
    name: "Keybase user lookup API",
    category: "username",
    tier: "tier1",
    keyRequired: false,
    accountRequired: false,
    paid: false,
    status: "verified",
    officialDocumentation: "https://keybase.io/docs/api/1.0/call/user/lookup",
    rateLimit: "Not published; gentle client-side pacing applied",
    automation: "permitted-rate-limited",
    input: "username or email",
    output: "Profile, full name, location, bio, PGP key, verified service proofs (Twitter/GitHub/Reddit/sites)",
    implementation: "https-json",
    limitations: "Service is in maintenance mode (Zoom acquisition) but the public API still responds.",
    defaultEnabled: true,
    lastVerified: "2026-09-03",
  },
  {
    id: "hackernews",
    name: "Hacker News / Firebase API (users)",
    category: "username",
    tier: "tier1",
    keyRequired: false,
    accountRequired: false,
    paid: false,
    status: "verified",
    officialDocumentation: "https://github.com/HackerNews/API",
    repository: "https://github.com/HackerNews/API",
    rateLimit: "None documented (Firebase-backed)",
    automation: "permitted",
    input: "username",
    output: "Karma, account creation date, about text, submission/comment history",
    implementation: "https-json",
    limitations: "Username must match exactly; no fuzzy search.",
    defaultEnabled: true,
    lastVerified: "2026-09-03",
  },
  {
    id: "cratesio",
    name: "crates.io users API",
    category: "code-registry",
    tier: "tier1",
    keyRequired: false,
    accountRequired: false,
    paid: false,
    status: "verified",
    officialDocumentation: "https://crates.io/data-access",
    repository: "https://github.com/rust-lang/crates.io",
    rateLimit: "1 req/second requested; User-Agent required",
    automation: "permitted-rate-limited",
    input: "username",
    output: "Rust crate author profile, GitHub link, avatar, account creation",
    implementation: "https-json",
    limitations: "Only covers published Rust crate authors.",
    defaultEnabled: true,
    lastVerified: "2026-09-03",
  },
  {
    id: "rubygems",
    name: "RubyGems.org profiles API",
    category: "code-registry",
    tier: "tier1",
    keyRequired: false,
    accountRequired: false,
    paid: false,
    status: "verified",
    officialDocumentation: "https://guides.rubygems.org/rubygems-org-api/",
    repository: "https://github.com/rubygems/rubygems.org",
    rateLimit: "10 req/second; anonymous GET allowed",
    automation: "permitted-rate-limited",
    input: "username",
    output: "Gem owner profile handle/id",
    implementation: "https-json",
    limitations: "Minimal payload (handle + id); richer data on the profile page.",
    defaultEnabled: true,
    lastVerified: "2026-09-03",
  },
  {
    id: "pypi",
    name: "PyPI user profiles (public HTML)",
    category: "code-registry",
    tier: "tier1",
    keyRequired: false,
    accountRequired: false,
    paid: false,
    status: "verified",
    officialDocumentation: "https://warehouse.pypa.io/api-reference/",
    repository: "https://github.com/pypi/warehouse",
    rateLimit: "Not published; fastly-cached public pages",
    automation: "permitted",
    input: "username",
    output: "Display name, owned projects with release dates, avatar (Gravatar)",
    implementation: "html",
    limitations: "No JSON profile API - profile page is parsed; 404 when user does not exist.",
    defaultEnabled: true,
    lastVerified: "2026-09-03",
  },
  {
    id: "npm",
    name: "npm user profiles (not keyless-verifiable)",
    category: "code-registry",
    tier: "tier3",
    keyRequired: false,
    accountRequired: false,
    paid: false,
    status: "unavailable",
    officialDocumentation: "https://github.com/npm/registry/blob/main/docs/REGISTRY-API.md",
    repository: "https://github.com/npm/registry",
    rateLimit: "N/A - the CouchDB user endpoint now returns 401 for all anonymous lookups",
    automation: "prohibited",
    input: "username",
    output: "Would-be npm profile",
    implementation: "https-json",
    limitations: "UNAVAILABLE keyless as of 2026-09: registry user endpoint requires auth (401), www.npmjs.com is an anti-bot-protected SPA whose terms prohibit scraping. Excluded from the default scan rather than guessing. Package-* metadata* endpoints remain public for domain/email work.",
    defaultEnabled: false,
    lastVerified: "2026-09-03",
  },
  {
    id: "dockerhub",
    name: "Docker Hub users API",
    category: "code-registry",
    tier: "tier1",
    keyRequired: false,
    accountRequired: false,
    paid: false,
    status: "verified",
    officialDocumentation: "https://docs.docker.com/docker-hub/api/latest/",
    rateLimit: "Anonymous GET allowed; 200 req/min authenticated",
    automation: "permitted-rate-limited",
    input: "username",
    output: "Full name, location, join date, Gravatar URL, profile type",
    implementation: "https-json",
    limitations: "Undocumented v2 endpoint but stable and used by the Hub UI itself.",
    defaultEnabled: true,
    lastVerified: "2026-09-03",
  },
  {
    id: "devto",
    name: "dev.to / Forem public users API",
    category: "username",
    tier: "tier1",
    keyRequired: false,
    accountRequired: false,
    paid: false,
    status: "verified",
    officialDocumentation: "https://developers.forem.com/api",
    repository: "https://github.com/forem/forem",
    rateLimit: "No key needed for reads; gentle pacing applied",
    automation: "permitted-rate-limited",
    input: "username",
    output: "Name, bio, location, Twitter/GitHub links, join date, avatar",
    implementation: "https-json",
    limitations: "Forem-powered (dev.to is the largest instance); other instances optional.",
    defaultEnabled: true,
    lastVerified: "2026-09-03",
  },
  {
    id: "stackexchange",
    name: "Stack Exchange API v2.3 (users)",
    category: "username",
    tier: "tier1",
    keyRequired: false,
    accountRequired: false,
    paid: false,
    status: "verified",
    officialDocumentation: "https://api.stackexchange.com/docs/users",
    rateLimit: "300 requests/day per IP without an app key; 10,000 with a free key",
    automation: "permitted-rate-limited",
    input: "username fragment (searches display names across Stack Overflow etc.)",
    output: "Display name, reputation, location, website, avatar, account age",
    implementation: "https-json",
    limitations: "Search is by display name (not login); returns fuzzy matches that must be judged.",
    defaultEnabled: true,
    lastVerified: "2026-09-03",
  },
  {
    id: "mastodon",
    name: "Mastodon / fediverse WebFinger (multi-instance)",
    category: "username",
    tier: "tier1",
    keyRequired: false,
    accountRequired: false,
    paid: false,
    status: "verified",
    officialDocumentation: "https://docs.joinmastodon.org/spec/webfinger/",
    repository: "https://github.com/mastodon/mastodon",
    rateLimit: "Per-instance; typically 300 req/5min, WebFinger is cheap",
    automation: "permitted-rate-limited",
    input: "username",
    output: "Profile URL, ActivityPub actor, avatar URL across major instances",
    implementation: "https-json",
    limitations: "Federated: a username may exist on any of thousands of instances; we probe a curated list of large instances.",
    defaultEnabled: true,
    lastVerified: "2026-09-03",
  },
  {
    id: "gravatar",
    name: "Gravatar profile API (by email hash)",
    category: "email",
    tier: "tier1",
    keyRequired: false,
    accountRequired: false,
    paid: false,
    status: "verified",
    officialDocumentation: "https://docs.gravatar.com/rest/hash/",
    repository: "https://github.com/Automattic/gravatar",
    rateLimit: "None documented for profile GETs",
    automation: "permitted",
    input: "email address (MD5-hashed client-side; address never sent)",
    output: "Display name, avatar, location, bio, verified accounts, photos",
    implementation: "https-json",
    limitations: "Only populated if the email owner created a Gravatar profile. Legacy profile JSON endpoint used.",
    defaultEnabled: true,
    lastVerified: "2026-09-03",
  },
  {
    id: "bluesky",
    name: "Bluesky public AppView API",
    category: "username",
    tier: "tier1",
    keyRequired: false,
    accountRequired: false,
    paid: false,
    status: "verified",
    officialDocumentation: "https://docs.bsky.app/docs/api/app-bsky-actor-get-profile",
    repository: "https://github.com/bluesky-social/atproto",
    rateLimit: "Public AppView; generous, rate limited per IP",
    automation: "permitted-rate-limited",
    input: "handle or DID",
    output: "Display name, bio, avatar, followers, join date, linked verification",
    implementation: "https-json",
    limitations: "Handle lookup only (no fuzzy search keyless); federated so other PDS instances exist.",
    defaultEnabled: true,
    lastVerified: "2026-09-03",
  },
  {
    id: "chesscom",
    name: "Chess.com public API",
    category: "username",
    tier: "tier1",
    keyRequired: false,
    accountRequired: false,
    paid: false,
    status: "verified",
    officialDocumentation: "https://www.chess.com/news/view/published-data-api",
    rateLimit: "No key; rate limited, must set descriptive User-Agent",
    automation: "permitted-rate-limited",
    input: "username",
    output: "Name, avatar, location, followers, join date, title, linked streaming accounts",
    implementation: "https-json",
    limitations: "Chess players only.",
    defaultEnabled: true,
    lastVerified: "2026-09-03",
  },
  {
    id: "lichess",
    name: "Lichess public API",
    category: "username",
    tier: "tier1",
    keyRequired: false,
    accountRequired: false,
    paid: false,
    status: "verified",
    officialDocumentation: "https://lichess.org/api",
    repository: "https://github.com/lichess-org/lila",
    rateLimit: "Keyless; stream endpoints are rate limited",
    automation: "permitted-rate-limited",
    input: "username",
    output: "Profile, bio, location, links, rating, activity, avatar",
    implementation: "https-json",
    limitations: "Chess players only.",
    defaultEnabled: true,
    lastVerified: "2026-09-03",
  },
  {
    id: "wikipedia",
    name: "Wikipedia/Wikimedia REST summary API",
    category: "username",
    tier: "tier1",
    keyRequired: false,
    accountRequired: false,
    paid: false,
    status: "verified",
    officialDocumentation: "https://en.wikipedia.org/api/rest_v1/",
    repository: "https://www.mediawiki.org/wiki/API:Main_page",
    rateLimit: "User-Agent header required; ~200 req/s for polite clients",
    automation: "permitted-rate-limited",
    input: "page title (person/entity name)",
    output: "Biographical summary, image, Wikidata id",
    implementation: "https-json",
    limitations: "Useful only when the target has a Wikipedia article; not a username checker.",
    defaultEnabled: false, // contextual - only useful for notable entities
    lastVerified: "2026-09-03",
  },

  // ---- Domain / network intelligence -------------------------------------
  {
    id: "rdap",
    name: "RDAP (Registration Data Access Protocol, IANA bootstrap)",
    category: "domain",
    tier: "tier1",
    keyRequired: false,
    accountRequired: false,
    paid: false,
    status: "verified",
    officialDocumentation: "https://rdap.iana.org/",
    repository: "https://data.iana.org/rdap/",
    rateLimit: "Per-registry; no keys; polite pacing",
    automation: "permitted-rate-limited",
    input: "domain or IP",
    output: "Registrar, events (registration/expiry), nameservers, DNSSEC, entities/contacts, abuse contacts",
    implementation: "https-json",
    limitations: "Coverage follows the IANA bootstrap file; ccTLD coverage varies. Replaces WHOIS with structured JSON.",
    defaultEnabled: true,
    lastVerified: "2026-09-03",
  },
  {
    id: "doh",
    name: "DNS-over-HTTPS (Google/Cloudflare JSON API)",
    category: "domain",
    tier: "tier1",
    keyRequired: false,
    accountRequired: false,
    paid: false,
    status: "docs-verified",
    officialDocumentation: "https://developers.cloudflare.com/1.1.1.1/encryption/dns-over-https/make-api-requests/dns-json/",
    rateLimit: "Free public resolvers; abuse-rate-limited",
    automation: "permitted-rate-limited",
    input: "domain + record type",
    output: "DNS records via HTTPS (works when plain DNS/53 is blocked)",
    implementation: "https-json",
    limitations: "Sees the resolver's view (not authoritative); fallback only when local DNS fails.",
    defaultEnabled: true,
    lastVerified: "2026-09-03",
  },
  {
    id: "crtsh",
    name: "crt.sh Certificate Transparency search",
    category: "domain",
    tier: "tier1",
    keyRequired: false,
    accountRequired: false,
    paid: false,
    status: "verified",
    officialDocumentation: "https://crt.sh/",
    repository: "https://github.com/crtsh",
    rateLimit: "No formal API limit; slow queries are killed after ~60s; cache + pace requests",
    automation: "permitted-rate-limited",
    input: "domain",
    output: "Issued certificates incl. wildcard names -> subdomain enumeration, CA history",
    implementation: "https-json",
    limitations: "Community service by Sectigo; can time out under load. Includes logged certs for all domains - do not misread wildcard entries.",
    defaultEnabled: true,
    lastVerified: "2026-09-03",
  },
  {
    id: "hacker-target",
    name: "HackerTarget free network tools",
    category: "domain",
    tier: "tier1",
    keyRequired: false,
    accountRequired: false,
    paid: false,
    status: "docs-verified",
    officialDocumentation: "https://hackertarget.com/ip-tools/",
    rateLimit: "50 free requests/day per IP (paid API key raises this)",
    automation: "permitted-rate-limited",
    input: "domain",
    output: "Hostlist from web search, DNS lookup, reverse IP",
    implementation: "https-json",
    limitations: "Daily cap is low; treated as a best-effort supplementary source.",
    defaultEnabled: true,
    lastVerified: "2026-09-03",
  },
  {
    id: "ipwhois",
    name: "ipwho.is geolocation & ASN (keyless)",
    category: "ip",
    tier: "tier1",
    keyRequired: false,
    accountRequired: false,
    paid: false,
    status: "verified",
    officialDocumentation: "https://ipwho.is/",
    rateLimit: "10,000 requests/month free, no key; HTTPS supported",
    automation: "permitted-rate-limited",
    input: "IPv4/IPv6 address",
    output: "Country/city/coords, ASN, ISP/org, timezone, flag",
    implementation: "https-json",
    limitations: "Free tier monthly cap; fallback providers documented in code.",
    defaultEnabled: true,
    lastVerified: "2026-09-03",
  },
  {
    id: "wayback",
    name: "Wayback Machine availability API",
    category: "domain",
    tier: "tier1",
    keyRequired: false,
    accountRequired: false,
    paid: false,
    status: "verified",
    officialDocumentation: "https://archive.org/help/wayback_api.php",
    repository: "https://github.com/internetarchive/wayback",
    rateLimit: "No formal limit; courtesy pacing",
    automation: "permitted-rate-limited",
    input: "URL/domain",
    output: "Closest archived snapshot URL + timestamp",
    implementation: "https-json",
    limitations: "Coverage depends on past crawls; CDX API offers full history (heavier).",
    defaultEnabled: true,
    lastVerified: "2026-09-03",
  },

  // =========================================================================
  // TIER 2 — FREE BUT REQUIRES AN ACCOUNT / KEY (optional, never default)
  // =========================================================================
  {
    id: "opt-github-token",
    name: "GitHub API with personal access token",
    category: "code-registry",
    tier: "tier2",
    keyRequired: true,
    accountRequired: true,
    paid: false,
    status: "optional-key",
    officialDocumentation: "https://docs.github.com/en/rest/overview/rate-limits-for-the-rest-api",
    rateLimit: "Raises 60/hour to 5,000/hour and enables email/commit search",
    automation: "permitted-rate-limited",
    input: "token in Settings",
    output: "Higher limits + authenticated search endpoints",
    implementation: "https-json",
    limitations: "Core app never requires it; token stored in browser localStorage only.",
    defaultEnabled: false,
  },
  {
    id: "opt-hibp",
    name: "Have I Been Pwned (breach data)",
    category: "email",
    tier: "tier2",
    keyRequired: true,
    accountRequired: false,
    paid: false,
    status: "key-required",
    officialDocumentation: "https://haveibeenpwned.com/API/v3",
    rateLimit: "Paid API key required for domain/breach lookups (k-anonymity password check is keyless)",
    automation: "key-only",
    input: "email",
    output: "Breaches the email appears in",
    implementation: "https-json",
    limitations: "KEY REQUIRED for breach search; not part of default scan.",
    defaultEnabled: false,
  },
  {
    id: "opt-virustotal",
    name: "VirusTotal public API",
    category: "domain",
    tier: "tier2",
    keyRequired: true,
    accountRequired: true,
    paid: false,
    status: "key-required",
    officialDocumentation: "https://docs.virustotal.com/reference/public-vs-premium-api",
    rateLimit: "4 requests/minute, 500/day on free key",
    automation: "key-only",
    input: "domain/IP/hash/URL",
    output: "Reputation, detections, relations graph",
    implementation: "https-json",
    limitations: "KEY REQUIRED; keyless web UI prohibits scraping - never automated without a key.",
    defaultEnabled: false,
  },
  {
    id: "opt-shodan",
    name: "Shodan API",
    category: "ip",
    tier: "tier2",
    keyRequired: true,
    accountRequired: true,
    paid: false,
    status: "key-required",
    officialDocumentation: "https://developer.shodan.io/api",
    rateLimit: "Scan/query credits; free tier very limited",
    automation: "key-only",
    input: "IP/domain",
    output: "Open ports, banners, services, vulnerabilities",
    implementation: "https-json",
    limitations: "KEY REQUIRED (and mostly paid).",
    defaultEnabled: false,
  },
  {
    id: "opt-urlscan",
    name: "urlscan.io API",
    category: "domain",
    tier: "tier2",
    keyRequired: true,
    accountRequired: true,
    paid: false,
    status: "key-required",
    officialDocumentation: "https://urlscan.io/docs/api/",
    rateLimit: "Submissions require a free API key; public search also key-gated now",
    automation: "key-only",
    input: "URL",
    output: "Page scan: DOM, requests, technologies, screenshot",
    implementation: "https-json",
    limitations: "KEY REQUIRED for submission/search.",
    defaultEnabled: false,
  },
  {
    id: "opt-wigle",
    name: "WiGLE WiFi/network database",
    category: "ip",
    tier: "tier2",
    keyRequired: true,
    accountRequired: true,
    paid: false,
    status: "key-required",
    officialDocumentation: "https://api.wigle.net/",
    rateLimit: "Free account tier with daily query limits",
    automation: "key-only",
    input: "SSID/BSSID/coords",
    output: "Observed networks and locations",
    implementation: "https-json",
    limitations: "KEY REQUIRED (account).",
    defaultEnabled: false,
  },
  {
    id: "opt-se-stackapps",
    name: "Stack Exchange app key (higher quota)",
    category: "username",
    tier: "tier2",
    keyRequired: true,
    accountRequired: true,
    paid: false,
    status: "optional-key",
    officialDocumentation: "https://api.stackexchange.com/docs/throttle",
    rateLimit: "Raises 300/day to 10,000/day",
    automation: "permitted-rate-limited",
    input: "app key in Settings",
    output: "Same keyless data, higher quota",
    implementation: "https-json",
    limitations: "Optional; keyless quota is enough for occasional investigations.",
    defaultEnabled: false,
  },

  // =========================================================================
  // TIER 3 — PAID / RESTRICTED (documented as future options only)
  // =========================================================================
  {
    id: "paid-pipl",
    name: "Pipl people search",
    category: "email",
    tier: "tier3",
    keyRequired: true,
    accountRequired: true,
    paid: true,
    status: "paid",
    officialDocumentation: "https://pipl.com/api",
    rateLimit: "Commercial contract",
    automation: "key-only",
    input: "email/name/phone",
    output: "Identity aggregation",
    implementation: "https-json",
    limitations: "PAID. Not part of default scan.",
    defaultEnabled: false,
  },
  {
    id: "paid-fullcontact",
    name: "FullContact identity resolution",
    category: "email",
    tier: "tier3",
    keyRequired: true,
    accountRequired: true,
    paid: true,
    status: "paid",
    officialDocumentation: "https://docs.fullcontact.com/",
    rateLimit: "Commercial",
    automation: "key-only",
    input: "email/phone",
    output: "Identity resolution",
    implementation: "https-json",
    limitations: "PAID.",
    defaultEnabled: false,
  },
  {
    id: "paid-leakcheck",
    name: "Leak-CX / breach lookup services",
    category: "email",
    tier: "tier3",
    keyRequired: true,
    accountRequired: true,
    paid: true,
    status: "paid",
    officialDocumentation: "https://leakcheck.io/api",
    rateLimit: "Commercial",
    automation: "key-only",
    input: "email",
    output: "Breach records",
    implementation: "https-json",
    limitations: "PAID; legal/ethical review recommended before use.",
    defaultEnabled: false,
  },

  // =========================================================================
  // EXCLUDED — investigated and deliberately NOT integrated
  // =========================================================================
  {
    id: "excl-reddit",
    name: "Reddit (excluded: automation blocked)",
    category: "username",
    tier: "tier3",
    keyRequired: true,
    accountRequired: true,
    paid: false,
    status: "unavailable",
    officialDocumentation: "https://www.reddit.com/dev/api/",
    rateLimit: "OAuth required for almost all endpoints; anonymous .json returns 403",
    automation: "prohibited",
    input: "username",
    output: "Would-be profile data",
    implementation: "https-json",
    limitations: "UNAVAILABLE without OAuth/account as of 2026; anonymous lookup returns HTTP 403. Excluded to respect terms.",
    defaultEnabled: false,
    lastVerified: "2026-09-03",
  },
  {
    id: "excl-instagram",
    name: "Instagram / Facebook / TikTok (excluded)",
    category: "username",
    tier: "tier3",
    keyRequired: true,
    accountRequired: true,
    paid: false,
    status: "unavailable",
    officialDocumentation: "https://developers.facebook.com/docs/instagram-api",
    rateLimit: "App review + business account required; scraping prohibited",
    automation: "prohibited",
    input: "username",
    output: "Would-be profile data",
    implementation: "https-json",
    limitations: "UNAVAILABLE: no keyless automated profile access; scraping prohibited by terms and actively blocked.",
    defaultEnabled: false,
  },
];

/** Quick lookup by id. */
export function getIntegration(id: string): Integration | undefined {
  return INTEGRATIONS.find((i) => i.id === id);
}

/** All sources enabled by default (tier 1 keyless). */
export function defaultEnabledIds(): string[] {
  return INTEGRATIONS.filter((i) => i.defaultEnabled && !i.keyRequired && !i.paid).map((i) => i.id);
}

/** Human-readable status badge text for the UI. */
export function statusLabel(s: Integration["status"]): string {
  switch (s) {
    case "verified": return "✓ Keyless source";
    case "docs-verified": return "✓ Keyless (network-restricted here)";
    case "local": return "✓ Local (no network)";
    case "optional-key": return "○ Optional API key";
    case "key-required": return "○ KEY REQUIRED";
    case "paid": return "○ PAID";
    case "unavailable": return "✕ UNAVAILABLE";
  }
}
